// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const createFallbackClient = () => {
  const error = new Error('Supabase is not configured in this environment. Please set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY environment variables.');

  return {
    auth: {
      getUser: async () => {
        console.error('[supabase] Cannot get user: Supabase not configured');
        return { data: { user: null }, error };
      },
    },
    from: () => ({
      insert: async () => {
        console.error('[supabase] Cannot insert data: Supabase not configured');
        return { error };
      },
    }),
    functions: {
      invoke: async () => {
        console.error('[supabase] Cannot invoke function: Supabase not configured');
        return { data: null, error };
      },
    },
  } as any;
};

const hasSupabaseEnv = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!hasSupabaseEnv) {
  console.error('[supabase] CRITICAL: Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY. Backend features (auth, save measurements, AI analysis) will NOT work.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = hasSupabaseEnv
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : createFallbackClient();
